version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: gym-tracker-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - gym-tracker-network
    restart: unless-stopped

networks:
  gym-tracker-network:
    driver: bridge