### Create Category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Strength Trainingg",
  "description": "Exercises focused on building muscle strength and power"
}

###

### Get Category by ID
GET http://localhost:3000/api/categories/8b78e38e-351d-4e16-9cdd-eb853fa80838

###
